name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert README.md to pdf
        run: |
          sudo apt install pandoc texlive-latex-extra
          mkdir -p _output
          ls -a
          pandoc README.md -o _output/readme.html
      
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: _output
          
          
