name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build book
        run: |
          sudo apt install pandoc texlive-latex-extra;
          pandoc README.md -f markdown -t html -o readme.html
          mkdir -p _output
      
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: _output
