name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert README.md to pdf
        run: |
          sudo apt-get install pandoc texlive-latex-base texlive-fonts-recommended texlive-extra-utils texlive-latex-extra
          pip install pandocfilters
          mkdir -p _output
          pandoc README.md -o README.pdf --filter=pandoc-svg.py
          
      
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: _output
          
          
