name: Convert README.md to PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert README.md to pdf
        run: |
          npm i -g md-to-pdf
          find . -name README.md -type f | while read file; do
            cat "$file" | md-to-pdf > ./"${file%/*}"/README.pdf
          done          
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated PDF
