name: Convert README.md to PDF

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci

      - name: Run Extension
        run: npm run build

      - name: Convert README.md to pdf
        run: |
          pip3 install grip
          npm i puppeteer --save
          find . -name README.md -type f | while read file; do
            cat "$file" | grip - --export ./"${file%/*}"/README.html
            node HtmlToPdf.js ./"${file%/*}"/README.html
            rm ./"${file%/*}"/README.html
          done          
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated PDF
