name: convert

on:
  push:

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Convert README.md to pdf
        run: |
          npm i -g md-to-pdf
          cat README.md | md-to-pdf > output.pdf
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated PDF
